### ISSUE TITLE
Introduction refers to TCP instead of TLS

### ISSUE THREAD

**Issue by jyasskin** [ioggstream/draft-polli-resource-digests-http#14]
https://github.com/ioggstream/draft-polli-resource-digests-http/blame/master/draft-polli-resource-digests-http.md#L117 should probably say

> Integrity protection for HTTP content is typically achieved via **TLS** or HTTPS [RFC2818].

**Comment by ioggstream** [comment]
I inherited the `TCP` from RFC3230, though in 2019 has a lot of more sense non mentioning TCP.

@LPardue could we say:

```
Integrity protection for HTTP content is typically achieved via TLS [RFC8446] or QUIC.
```

Otherwise I would just mention TLS.

**Comment by LPardue** [comment]
Ok I think I see what happened here. RFC 3230 had a whole lot of text about how integrity applies throughout the entire TCP stack. Our refactor loses that, and the sentence that @jyasskin points out can be misinterpreted.

Given it is the opening sentence I think we should change things back in the original direction but maybe more concisely.
Below is my initial response before taking a step back and seeing what the real problem is here.

_Integrity is multi layered.

The intent of the sentence that I have is that it tries to explain that hops have integrity methods below layer 7: ethernet checksum, IP checksum, TCP checksum, TLS record, etc.

No matter how weak the algorithms may be, receivers that validate integrity do have an effect on the transfer of the data, and give confidence to the higher layer. Sadly, the HTTP layer doesn't do integrity checking for the most part - digest allows that.

Changing this sentence to just TLS does a disservice to all of the integrity checking through the IP stack._

**Comment by jyasskin** [comment]
I think I've been living too closely to cryptographic systems. Yes, it makes sense to talk about transport-layer protocols that protect integrity from random corruption even if they're not secure against clever attackers.

**Comment by LPardue** [comment]
Times change and we should have affordance for today's audience. I think we can address this straightforwardly.

**Comment by ioggstream** [comment]
@LPardue close if you like the solution ;)

**Comment by LPardue** [comment]
I like the solution but don't have permission to close the issue :D

**Comment by ioggstream** [comment]
Closed :D
